<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ADMIN', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . "admin" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_FRONTEND', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . "frontend" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_LANGUAGES', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . "languages" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_TEMPLATES', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . "templates" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_CACHE', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . "cache" . DIRECTORY_SEPARATOR );
$plugin_url = plugins_url( '', __FILE__ );
$plugin_url = str_replace( '/includes', '', $plugin_url );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS', $plugin_url . "/assets/" );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS_DIR', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . "assets" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_PACKAGES', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS_DIR . "packages" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_CSS', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS . "css/" );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_CSS_DIR', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS_DIR . "css" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_JS', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS . "js/" );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_JS_DIR', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS_DIR . "js" . DIRECTORY_SEPARATOR );
define( 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_IMAGES', SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ASSETS . "images/" );
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'functions.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'data.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'subscription-product-helper.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'subscription-order.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'subscription-email.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'subscription-schedule.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'subscription-actions.php';
require_once SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'trait-order-list-table.php';
vi_include_folder( SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_ADMIN, 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_Admin_' );
vi_include_folder( SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_FRONTEND, 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_Frontend_' );
vi_include_folder( SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_INCLUDES . 'payment' . DIRECTORY_SEPARATOR, 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_Payment_' );
vi_include_folder( SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_DIR . 'compat' . DIRECTORY_SEPARATOR, 'SUBRE_PRODUCT_SUBSCRIPTION_FOR_WOO_Compat_' );